[phases.setup]
nixPkgs = [
    "python39",
    "python39Packages.pip",
    "python39Packages.virtualenv"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"